version: "3.8"

networks:
  laravel:
    driver: bridge

services:
  hexcubserver:
    image: nginx:alpine
    container_name: hexcubserver
    restart: unless-stopped
    tty: true
    ports:
      - "7000:80"
      - "443:443"  # membuka akses HTTPS
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/app:delegated
      - ./nginx/certs:/etc/letsencrypt:ro  # mount sertifikat SSL ke nginx
    depends_on:
      - hexcubapi
    networks:
      - laravel

  hexcubapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hexcubapi
    restart: unless-stopped
    tty: true
    expose:
      - "9000"
    volumes:
      - .:/var/www/app:delegated
    networks:
      - laravel
