version: "3.8"

networks:
  laravel:
    driver: bridge

services:
  hexcubserver:
    image: nginx:alpine
    container_name: hexcubserver
    restart: unless-stopped
    tty: true
    expose:
      - "80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/app:delegated
    depends_on:
      - hexcubapi
    networks:
      - laravel

  hexcubapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hexcubapi
    restart: unless-stopped
    tty: true
    expose:
      - "9000"
    volumes:
      - .:/var/www/app:delegated
    networks:
      - laravel

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - "8080:80"     # Untuk HTTP (akses lokal, optional)
      - "8443:443"    # Untuk HTTPS
      - "8282:81"     # Untuk akses UI NPM
    volumes:
      - ./nginx-data/data:/data
      - ./nginx-data/letsencrypt:/etc/letsencrypt
    networks:
      - laravel
