version: "3.8"

networks:
  laravel:
    driver: bridge

services:
  hexcubserver:
    image: nginx:alpine
    container_name: hexcubserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"        # Akses langsung tanpa :7000
      - "443:443"      # Akses HTTPS
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www/app:delegated
      - ./nginx/certs/cert.pem:/etc/ssl/cert.pem:ro
      - ./nginx/certs/key.pem:/etc/ssl/key.pem:ro
    depends_on:
      - hexcubapi
    networks:
      - laravel

  hexcubapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hexcubapi
    restart: unless-stopped
    tty: true
    expose:
      - "9000"
    volumes:
      - .:/var/www/app:delegated
    networks:
      - laravel

  # Uncomment and modify if using certbot for Let's Encrypt
  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   depends_on:
  #     - hexcubserver
  #   volumes:
  #     - ./nginx/certs:/etc/letsencrypt
  #     - ./nginx/letsencrypt:/var/lib/letsencrypt
  #     - ./nginx/html:/var/www/html
  #   command: certonly --webroot --webroot-path=/var/www/html --email you@example.com --agree-tos --no-eff-email -d hexcubapi.zqdevs.my.id
