version: "3.8"

networks:
  laravel:
    driver: bridge

services:
  hexcubapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hexcubapi
    restart: unless-stopped
    tty: true
    expose:
      - "9000"
    volumes:
      - .:/var/www/app:delegated
    networks:
      - laravel

  hexcubserver:
    image: nginx
    container_name: hexcubserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"        # Akses langsung tanpa :7000
      - "443:443"      # Akses HTTPS
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www/app:delegated
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      # ❌ HAPUS YANG INI:
      # - ./nginx/cert/fullchain.pem:/etc/ssl/cert.pem:ro
      # - ./nginx/cert/privkey.pem:/etc/ssl/privkey.pem:ro
    depends_on:
      - hexcubapi
    networks:
      - laravel

  # Uncomment and modify if using certbot for Let's Encrypt
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email afn.happy@gmail.com -d hexcubapi.zqdevs.my.id --agree-tos
